version: '2'
services:
  mongodb:
    image: mongo
  pally:
    build: .
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    ports:
      - '3000:3000'
      - '4000:4000'
    depends_on:
      - mongodb
